#cloud-config

# cloud-init 18.3
# http://cloudinit.readthedocs.io/en/18.3/index.html

hostname: black-pearl
manage_etc_hosts: true

users:
  - name: pirate
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users, docker, video
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

package_update: true
package_upgrade: false
package_reboot_if_required: true
packages:
  - ntp
  - libnss-mdns

locale: "en_US.UTF-8"
timezone: "Europe/Berlin"

# tell docker to tag this node appropriately
write_files:
  - path: "/etc/docker/daemon.json"
    owner: "root:root"
    content: |
      {
        "labels": [ "os=linux", "arch=arm64" ],
        "experimental": true
      }

# run commands (on first boot only)
runcmd:
  # pickup hostname
  - [ systemctl, restart, avahi-daemon ]

  # pickup daemon.json changes
  - [ systemctl, restart, docker ]

  # init docker swarm (make sure address pool doesn't conflict)
  - [ docker, swarm, init, --default-addr-pool, 10.20.0.0/16, --default-addr-pool-mask-length, 24 ]
  - [ docker, network, create, --driver=overlay, --attachable, traefik ]

  # clone docker stacks
  - ' git clone https://github.com/witsch/stacks /etc/docker/stacks '

  # run traefik & pihole
  - [ docker, stack, deploy, --compose-file=/etc/docker/stacks/traefik.yaml, traefik ]
  - [ docker, stack, deploy, --compose-file=/etc/docker/stacks/pihole.yaml, pihole ]
  - [ docker, stack, deploy, --compose-file=/etc/docker/stacks/portainer.yaml, portainer ]
  - [ docker, stack, deploy, --compose-file=/etc/docker/stacks/nextcloud.yaml, nextcloud ]

  # setup dnsmasq to make host available as *.pi
  - [ bash, /etc/docker/stacks/dnsmasq-config.sh ]
