#cloud-config

# cloud-init 18.3
# http://cloudinit.readthedocs.io/en/18.3/index.html

hostname: black-pearl
manage_etc_hosts: true

users:
  - name: pirate
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users, docker, video
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - ntp

locale: "en_US.UTF-8"
timezone: "Europe/Berlin"

# tell docker to tag this node appropriately
write_files:
  - path: "/etc/docker/daemon.json"
    owner: "root:root"
    content: |
      {
        "labels": [ "os=linux", "arch=arm64" ],
        "experimental": true
      }

# run commands (on first boot only)
runcmd:
  # pickup hostname
  - [ systemctl, restart, avahi-daemon ]

  # pickup daemon.json changes
  - [ systemctl, restart, docker ]

  # init docker swarm
  - [ docker, swarm, init ]
