version: "3.7"

services:
  app:
    image: nextcloud
    environment:
      - SQLITE_DATABASE=cloud
    volumes:
      - nextcloud:/var/www/html
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.pi`)"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

volumes:
  nextcloud:

networks:
  traefik:
    external: true
