version: "3.7"

# more info at https://github.com/pi-hole/docker-pi-hole/
# and https://docs.pi-hole.net/

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: Europe/Berlin
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    deploy:
      replicas: 1

volumes:
  pihole:
  dnsmasq:
