version: '3.7'

services:
  proxy:
    image: traefik:v2.2
    command:
      - '--api.insecure=true'
      - '--entryPoints.web.address=:80'
      - '--providers.docker=true'
      - '--providers.docker.swarmMode=true'
      - '--providers.docker.network=traefik'
      - '--accesslog=true'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '80:80'
      - '8080:8080'
    deploy:
      replicas: 1
      restart_policy:
        window: 120s
      labels:
        - "traefik.http.routers.proxy.rule=Host(`traefik.pi`)"
        - "traefik.http.routers.proxy.entrypoints=web"
        - "traefik.http.services.proxy.loadbalancer.server.port=8080"
    networks:
      - traefik

networks:
  traefik:
    external: true
